### ISSUE TITLE
Error when pressing Pokemon Editor ( 1.0.3 )

### ISSUE THREAD

**Issue by Kreygasm13** [svfeplvce/ProjectSky#2]
[log.txt](https://github.com/svfeplvce/ProjectSky/files/10336518/log.txt)

Cannot open editor at all.  With Error of "Value cannot be null. (Parameter 'stream')"

Installed Latest NET 7.0 again but no avail.

**Comment by Kreygasm13** [comment]
Also I just realized. Its trying to take user named "foxna" which is NOT my username in my PC.

Still not sure though.

**Comment by svfeplvce** [comment]
fixed in v1.0.2(?)

was an issue where i accidentally included my config.json in a release

**Comment by Kreygasm13** [comment]
Sorry to bother again but Problem for some reason still persists in 1.0.3 .

If this is because of my System Language It would make a bit sense.
