### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. (Parameter 'stream')

### ISSUE THREAD

**Issue by Kreygasm13** [svfeplvce/ProjectSky#5]
Duplicate of Issue 2#

An Error that is somehow only ( maybe ) persisting on my own end.

No changes to config.json , Fresh Install and same issue appears.

[log (1).txt](https://github.com/svfeplvce/ProjectSky/files/10377643/log.1.txt)

**Comment by svfeplvce** [comment]
can you send the config.json file you are using as well as the version you are using?

**Comment by svfeplvce** [comment]
also make sure to leave the desired output path in the message you send. thank you :)

**Comment by Kreygasm13** [comment]
[config.txt](https://github.com/svfeplvce/ProjectSky/files/10379030/config.txt)
Converted to TXT since Github do not support uploading JSON.

I am using latest 1.0.4

Config JSON is fresh after chosing a folder.

**Comment by svfeplvce** [comment]
hmm. it would appear as though the issue is NOT your config file after all. what is also odd is that your issue cannot be replicated on my end despite the fact that i programmed the damn thing. try [this](https://github.com/svfeplvce/ProjectSky/files/10379275/projskytest.zip).

**Comment by Kreygasm13** [comment]
Tried it again. Gave it out an error again and with the file you sent to me.

Honestly First thing I got suspicous of was System Language of mine due to it having "İ ı ğ ü ç ö"

[error.log](https://github.com/svfeplvce/ProjectSky/files/10380703/error.log)
[config.txt](https://github.com/svfeplvce/ProjectSky/files/10380705/config.txt)

**Comment by svfeplvce** [comment]
i am so confused... the issue here seems to be that the program is trying to find resources in a folder on your computer that doesnt exist since its on MY computer, but i have no idea why. ill get back to you in a bit hopefully and see whats going on=.

**Comment by svfeplvce** [comment]
fixed in 1.0.5

**Comment by Kreygasm13** [comment]
> fixed in 1.0.5

I am not sure...

It is giving me same error on 1.0.5 and I still don't know why.
